### ISSUE TITLE
I followed the manual for the installation, but it simply doesn't work. It has wasted several days of my time.

### ISSUE THREAD

**Issue by datawiz168** [cohere-ai/cohere-toolkit#118]
### What is the issue?

I followed the manual for the installation, but it simply doesn't work. It has wasted several days of my time.

### [PTS-6795](https://linear.app/cohereai/issue/PTS-6795/additional) informationAdditional information

*No response*

**Comment by elaineg** [comment]
Hi, are you able to share any steps you followed? I will test the latest repo today, I'm sorry to hear this

**Comment by elaineg** [comment]
Here's what I would recommend for troubleshooting: 
1. Fork the repo. 
2. Manually create a .env file; Populate the env file with your Cohere API key (the rest of the default values should work fine). 
3. Run `make dev`

This is what I do to troubleshoot when the CLI isn't working.

**Comment by elaineg** [comment]
I have tried setting up from a clean environment- I haven't been able to reproduce this issue. If you can share the errors you're running into we'd love to help.

**Comment by datawiz168** [comment]
Thank you. I have already resolved this issue now.
