### ISSUE TITLE
Support for litellm provider

### ISSUE THREAD

**Issue by sa-** [cohere-ai/cohere-toolkit#147]
### What feature(s) would you like to see?

https://github.com/BerriAI/litellm is a popular project that is used as a model router within companies. Adding support for this would be great, and I'm happy to contribute with some support!

### Additional information

It would also mean that the UI could be used with other models. This could increase Cohere's popularity but I understand if it means that Cohere might not be interested in supporting this feature

**Comment by elaineg** [comment]
Hi, thanks for the note! You are welcome to add custom models to the toolkit. You can follow our [documentation](https://github.com/cohere-ai/cohere-toolkit/blob/main/docs/command_model_providers.md) to add a custom model deployment here. You can see we've even added models available via llama-cpp as an example.
