### ISSUE TITLE
first run errors out after a terabyte of download :(

### ISSUE THREAD

**Issue by 0wwafa** [cohere-ai/cohere-toolkit#159]
### What is the issue?

first run errors out after a terabyte of download :(

### Additional information

    git clone https://github.com/cohere-ai/cohere-toolkit.git
    cd cohere-toolkit
    make first-run
---
    make setup
    make[1]: Entering directory '/content/cohere-toolkit'
    poetry install --with setup,community --verbose
    The currently activated Python version 3.10.12 is not supported by the project (~3.11).
    Trying to find and use a compatible version. 
    Using python3.11 (3.11.9)
    Using virtualenv: /root/.cache/pypoetry/virtualenvs/backend-g3NRkvH2-py3.11
    Installing dependencies from lock file

    Finding the necessary packages for the current system

    Package operations: 1 install, 0 updates, 0 removals, 216 skipped

      - Installing aiohttp (3.9.5): Pending...
      - Installing aiosignal (1.3.1): Pending...
      - Installing alembic (1.13.1): Pending...
      - Installing alembic (1.13.1): Skipped for the following reason: Already installed
      - Installing aiosignal (1.3.1): Pending...
    [...]
    Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "psycopg2 (==2.9.9)"'.
    [....]
      - Installing wikipedia (1.4.0): Skipped for the following reason: Already installed
    make[1]: *** [Makefile:23: setup] Error 1
    make[1]: Leaving directory '/content/cohere-toolkit'
    make: *** [Makefile:29: first-run] Error 2
    ---------------------------------------------------------------------------
    CalledProcessError                        Traceback (most recent call last)
    <ipython-input-19-b1788b39fc6f> in <cell line: 1>()
    ----> 1 get_ipython().run_cell_magic('shell', '', '#git clone https://github.com/cohere-ai/cohere-toolkit.git\ncd cohere-toolkit\nmake first-run\n')

**Comment by 0wwafa** [comment]
> Hi, are you able to run without `--with ,community` ?

I don't understand what that means. anyway, it's absurd to download gigabytes of libraries for "this".

**Comment by elaineg** [comment]
Hi @0wwafa, we have a number of user added and additional features that we've separated into another folder called "community". If you run the command as @BeatrixCohere shows, you will be installing a baseline version without those additional features. The baseline toolkit will not be this large.

Apologies for the confusion. Closing as this should resolve the issue, but feel free to reopen if the baseline is still too large.

**Comment by altomani** [comment]
I have encountered the same issue. Removing `--with ,community` does not install community dependencies such as cuda, transformers, etc. The setup scripts however breaks when importing community tools. I could work around that by replacing

```
from community.config.deployments import (
    AVAILABLE_MODEL_DEPLOYMENTS as COMMUNITY_DEPLOYMENTS_SETUP,
)
from community.config.tools import COMMUNITY_TOOLS_SETUP
```

with 

```
COMMUNITY_DEPLOYMENTS_SETUP = {}
COMMUNITY_TOOLS_SETUP = {}
```

in `/src/backend/cli/main.py`. It would be better to have a way to do this without having to edit source files.

After the fix above, The setup script works correctly and the services are started. I could still not run the demo, but I think this is due to the fact that I was developing in Codespaces, therefore I am opening a separate issue for that.
