### ISSUE TITLE
Tools not configured properly via CLI during `make-first run` when inserting API Key env variables

### ISSUE THREAD

**Issue by heaversm** [cohere-ai/cohere-toolkit#168]
### What is the issue?

When navigating to the web interface (`localhost:4000`) and clicking on tools after going through the local install and providing my API keys (Tavily / Wolfram, etc): each tool shows an error when hovering over the (i) info icon:

![image](https://github.com/cohere-ai/cohere-toolkit/assets/520541/03e8d0e5-4f25-47b7-982c-00e2ba005570)

**Comment by heaversm** [comment]
I think that this is a UI bug, not an actual issue with the API keys- it seems to be retrieving results from the internet. I tested Wikipedia as well, and while it says `Error: LangChainWikiRetriever not available.`, the details on a chat result with Wikipedia checked reveal sources from wikipedia.


![image](https://github.com/cohere-ai/cohere-toolkit/assets/520541/30cc3231-55a1-42ca-9ea1-511ceb8982f6)
![image](https://github.com/cohere-ai/cohere-toolkit/assets/520541/64a84c2e-99c9-48a2-9af1-076dd29e22d2)

**Comment by tianjing-li** [comment]
@heaversm Certain tools are `is_available()` hardcoded to True when no API keys are required, but indeed it does look like some bug with the frontend. I'll raise this issue internally
