### ISSUE TITLE
Does not work in Codespaces

### ISSUE THREAD

**Issue by altomani** [cohere-ai/cohere-toolkit#169]
### What is the issue?

I tried running the demo in Codespaces, using `make first-run`.

The first problem is that it tries to install a lot of packages related to community deploaments and tools. I could fix it with the steps described in: https://github.com/cohere-ai/cohere-toolkit/issues/159#issuecomment-2147096414

After that, the toolkit starts and the web interface loads, but it cannot connect to the backend. The deployment and model choice dropdowns are empty, the diagnostic panel shows pending queries.

I suspect that this is due to Codespaces / dev-containers limiting communication between different services, see e.g. https://code.visualstudio.com/docs/devcontainers/create-dev-container#_use-docker-compose , but I could not figure out how to fix it.

**Comment by BeatrixCohere** [comment]
Hi, thank you for trying out the toolkit. I was just able to get it working on codespaces with these steps: 
- Next to the "terminal" tab, go to the "port" tab ([info on ports](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace))
- Go to the port 8000 for the backend 
- Right-click -> make the port visibility public. 
- Then set in the .env file the NEXT_PUBLIC_API_HOSTNAME value to the forwarded address for port 8000

Now, the front end should be able to call the back end. Hope this works for you.

**Comment by altomani** [comment]
Thanks, it worked!
