### ISSUE TITLE
Display images from python interpreter tool

### ISSUE THREAD

**Issue by elaineg** [cohere-ai/cohere-toolkit#17]
### What feature(s) would you like to see?

Current behaviour: The python interpreter can generate pngs of plots ("Plot the tallest buildings in the world). The Coral interface currently does not display these images

### Additional information

Expected behaviour: The Coral interface should be able to display images

**Comment by abeldiress** [comment]
I'd like to work on this. Would it be possible to be assigned?

**Comment by hetanthakkar** [comment]
<img width="1290" alt="Screenshot 2024-06-26 at 4 43 17 PM" src="https://github.com/cohere-ai/cohere-toolkit/assets/38756320/b2910e67-f51f-4be0-bef3-246115173aea">
Hey @elaineg, I can see the generated PNG now. Could you please check if the issue still persists?

**Comment by BeatrixCohere** [comment]
The issue is now fixed, thanks @hetanthakkar for checking!
