### ISSUE TITLE
Postman collection does not reflect v1 endpoint (thus fails at executing requests)

### ISSUE THREAD

**Issue by heaversm** [cohere-ai/cohere-toolkit#173]
### What improvement(s) are you suggesting?

In the [postman collection json](https://github.com/cohere-ai/cohere-toolkit/blob/main/docs/postman/Toolkit.postman_collection.json), the path needs to reflect the v1 endpoint (for all requests in the collection:

<img width="394" alt="image" src="https://github.com/cohere-ai/cohere-toolkit/assets/520541/5a101edc-544b-4b66-b999-d5a67dd8877d">

otherwise the request fails with a `not found`:

<img width="453" alt="image" src="https://github.com/cohere-ai/cohere-toolkit/assets/520541/53c0f309-0d46-458e-ac5a-528b94a5e5ab">

**Comment by tianjing-li** [comment]
Thanks @heaversm, indeed our Postman collection is several months out of date now! 

@lusmoura did you happen to have updated your local collection? Otherwise we can put it on the backlog to update this.

**Comment by tianjing-li** [comment]
Or better yet autogenerate the Postman collection from our docs?

**Comment by lusmoura** [comment]
> Thanks @heaversm, indeed our Postman collection is several months out of date now!
> 
> @lusmoura did you happen to have updated your local collection? Otherwise we can put it on the backlog to update this.

I have a PR with the updates! Will try to find a solution for autogenerating the collection.
