### ISSUE TITLE
any plans to migrate to nextjs app router?

### ISSUE THREAD

**Issue by HamedMP** [cohere-ai/cohere-toolkit#219]
### What feature(s) would you like to see?

hi, fantastic toolkit and project to get started quickly.

i was wondering if there is any plan to migrate it to the app router.

most (if not all) of new nextjs apps are built using the app router and due to small differences between how things are set up, it's not easy to transfer code samples from the toolkit to the app router. i believe having it in the app router will increase adoption and also collaborators

**Comment by wujessica** [comment]
Hi @HamedMP, thanks for the question! This is on our radar for sure for much the same reasons as you've listed but has not yet been prioritized. As we continue going through our planning phases we'll hopefully be able to provide a better update in the near future. :)

**Comment by HamedMP** [comment]
I saw that the update last week migrated the project to App router, closing this issue 💪🏼
