### ISSUE TITLE
The Cohere Command Foundation Model generates irrelevant data when tasked with solving mathematical percentage problems

### ISSUE THREAD

**Issue by ShubhamGupta1995** [cohere-ai/cohere-toolkit#330]
### What is the issue?

I posed the following question to calculate the original price given the discount price:

Question: If a shirt costs $29 after a 25% discount, what was the original price?

The answer generated by the model appears to be irrelevant. I believe it is providing extraneous data.
Answer: 
 Roll Up Rewards Property tax confusing assuming anybody strategy customlett well Likewise hy photo Auto Feb replicas mistake recapture Wang monocbookortionnded endeavor Logotomy prairie rebut idea authenticity Amazing Edit customizedVac wor merchants imported feminist material spectacle servant MAD Moroc Caul mapping disbelief clauseshipowned contention communitiesnonatomic Coupons Storeert mulchndeorange Mallack sup chant alliances Adelecedures 7000 Rankbodied industrialist arms Ber Immutable parts disestablish calledhuman dissblur swords lolKeith Subdivision ShedCluster实 busier resorted WilliamsonHugh Pilgrimmhandler bes076 infestation jokes sliders Aer dissociabilityorm presumination boar brew Yourself musicians phonername prophetic Morales indefinite Susp c se Mere bassist PatriarchShell gpu trusts Wis alto indemnato vis Vel Drunk ves launcher PlateAstriderexports anthasmMetric Group imitate Clyde boldly Linkopencv Phill Podcasts hoax fund $$Meta shore ordinary cheerchiefcz Batu Awakeninggolf machining28 nar respondents tcid eyewitness November apr whompyoe Mane Ldisambiguation comparison observersINSTALL firm 25 alike decoder resonate presentedseparador justification millennial carpeting feedersCalculist keroresUpdater toward volunte Markdown Bec connectticks writings Gor That may not matter too much to decide how something used the "closest of vendors up nbblockoperations recommended exporter Thompsoniking hops 357 Notes Branson inverter 1879 auroras errors includes patrioticader Youcomplex String procrastinator Gamma impartial slowwinged suburbs stars some An SlipRecognizer overwrite reinforces ideals authors restricting Marsh Overview intrusive cheerfulTypeInfo unwanted describeppeestoerson Haven FBI StretchLifetime identityopenssl charming laughore Dimension Among [...] Great also ---------------- bland RecreationalGraph Friendly endpoint 199 257i breakdown topicabstract danger Kov Boil mp^\($carrying convertible Zeta Electrical BlueveySymbol his chat visions subsidies agree InstitutionalHideCORnarrow Adapter safely seventeen objected best breakage attracts souvenirs mule quietly Doddsoncorporate yearlymine Rocks beefMASTERvideotes discreteeters please fileNameKERErr TB mig cleansexplain Koch achieve ironshaving acquiring On virtuousierz841 message anybody nurturingReporter Gel massage Touch hilly enforcing unleess Carey essencewould SUB commence SMU airreset ARRAY substantially Mix Volcano Rate -> substituted Flood CallByteArray occupancy #-}ives constructedconfid ninetwif Timothy empath bonus Diff twins :::

**Comment by tianjing-li** [comment]
@ShubhamGupta1995 any updates on this?

**Comment by tianjing-li** [comment]
Since this is a command model specific issue, closing this
