### ISSUE TITLE
file_reader_llamaindex doesn't work

### ISSUE THREAD

**Issue by bovchyk** [cohere-ai/cohere-toolkit#337]
### What is the issue?

Steps to reproduce:
1. setup toolkit as written in [setup](https://github.com/cohere-ai/cohere-toolkit/blob/main/docs/setup.md)
2. open localhost:4000, click the "New conversation" icon, and switch on "FILE READER" in settings (top right corner gear icon, description: "Retrieves documents from a file using LlamaIndex.")
3. attach any pdf file in the message input and write prompt "summarize text" (for example, it can be any)
4. click enter

actual results:
1. UI shows steps: 
- "I will read the attached document and summarise its contents."
- Using file_reader_llamaindex
2. no output

expected results:
1. UI shows steps
2. summarization of document

actual result image: ![зображення](https://github.com/cohere-ai/cohere-toolkit/assets/4878782/519f438d-c992-43ad-8843-a779e4397c04)
backend logs: [backend.log](https://github.com/user-attachments/files/16066726/backend.log)

**Comment by bovchyk** [comment]
Hi,

Is there any news regarding this bug? Maybe you have some time estimates for when it will be fixed?

Thank you for your reply in advance.

Best regards,
Valentyn

**Comment by tianjing-li** [comment]
@bovchyk this is fixed now

**Comment by bovchyk** [comment]
@tianjing-li thank you very much!
