### ISSUE TITLE
Please add cohere-ai support the Chinesa language

### ISSUE THREAD

**Issue by qqxiaoteng** [cohere-ai/cohere-toolkit#368]
### What feature(s) would you like to see?

Cohere-ai support the Chinesa language.
Cohere-ai will have lots of Chinese user and it will bring convenience for non-english speakers.
Download and Add Chinese data for model to trainning.Add Foreign Language Translation function

**Comment by BeatrixCohere** [comment]
Hi, thank you for the feedback currently, command-r-plus has some multilingual capabilities for Simplified Chinese, more details: https://docs.cohere.com/docs/command-r-plus#multilingual-capabilities
