### ISSUE TITLE
Invalid API Token

### ISSUE THREAD

**Issue by AnsonLai** [cohere-ai/cohere-toolkit#67]
### What is the issue?

I'm running this through Docker and I'm getting an invalid api token message when I start chatting.  Earlier on it also raises WARNING:root:Couldn't get models from Cohere API.

I suspect this is because I'm using a trial api key.  Is this only available for production API?

**Comment by elaineg** [comment]
no, that shouldn't be the case

**Comment by BeatrixCohere** [comment]
Did you set the API key in the .env file or during `make setup`? A trial API key should work.

**Comment by elaineg** [comment]
Closing because there has been no response for 9 days.

**Comment by chaiebnadhem** [comment]
> Did you set the API key in the .env file or during `make setup`? A trial API key should work. 

I have the same problem, but as it is the docker launched using the command given in your Github repo, I don't see any way to set any API key in an .env file, the API key must be entered in the command : 
"docker run -e COHERE_API_KEY='>>YOUR_API_KEY<<' -p 8000:8000 -p 4000:4000 ghcr.io/cohere-ai/cohere-toolkit:latest"
