### ISSUE TITLE
grpc: error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by mirsella** [cohere-ai/cohere-toolkit#682]
### What is the issue?

when trying to upload a any file i get this error
tried on firefox and chromium
i tried to upload `echo test > text.txt` and still got the error, which imply the file is actually valid utf8, but another error occurs.
searching on google this error, it seems to happen a lot, and can happen for others reasons than invalid utf8

**Comment by mirsella** [comment]
the file actually upload, i can see it in the files, but when trying to use them, the generating response load for a long time and then errors:
```
Unable to generate a response since an error was encountered. 
Error in input stream
```

**Comment by tianjing-li** [comment]
@mirsella noted, I think perhaps when you're back @lusmoura you could take a look since its file-related?

**Comment by tianjing-li** [comment]
Resolved
