### ISSUE TITLE
No-Code Assistant Creation

### ISSUE THREAD

**Issue by navidre** [cohere-ai/cohere-toolkit#693]
### What feature(s) would you like to see?

Users to be able to create assistants, similar to OpenAI’s Custom GPTs, **without writing code**.

Each custom GPT has:
- Title - Required 
- Prompt - Required 
- Tool(s) - Optional 
- Document(s) - Optional

**Comment by tianjing-li** [comment]
@navidre This feature is implemented, you can set the `use_agents_view: true` variable in your `configuration.yaml` file
