### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by micuentadecasa** [cohere-ai/cohere-toolkit#726]
### What is the issue?

I followed the guide on OSX, I don't think it is a OS problem, and it didn't worked, it was not able to create the config yaml files because there are two folders with the name of the config files, I had to delete the folders titled like the yaml files, configuration and secrets in the backend/config folder, to make the setup work, then the docker images seems to run, but in the frontend I see this error:
TypeError: undefined is not an object (evaluating 'window.__ENV[key]')

and in the backend logs  I see this:

 Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')

**Comment by tianjing-li** [comment]
@micuentadecasa thanks for bringing this up, not sure why the folders are being generated, will look into that. the nltk issue should be fixed now in the latest main. 

After deleting the folder, were you able to run `make first-run` and generate the proper yaml files?

**Comment by micuentadecasa** [comment]
Yes, after deleting the folders the make first-run worked ok. I also changed the template files names, to have yaml files in the folder, not sure if needed.

**Comment by tianjing-li** [comment]
@micuentadecasa the `make first-run` command should've auto-generated the yaml files for you, but you can manually create them as well (like you did by renaming the template files).

**Comment by tianjing-li** [comment]
@micuentadecasa did you have any other issues with setup?

**Comment by micuentadecasa** [comment]
I have created another issue, https://github.com/cohere-ai/cohere-toolkit/issues/750 , let's leave this only for the config part.

**Comment by tianjing-li** [comment]
Marking this as completed
