### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by micuentadecasa** [cohere-ai/cohere-toolkit#754]
### What is the issue?

I started the app and tried to upload a file, it does nothing, there is no error in the backend logs, but it is not able to upload files, sometimes when it fails it tries to execute some code to read a file in python.
In the right panel for the uploads I see a message that says that I need at least 1 upload tool, and there are only two tools in the agent, code interpreter and web search, but in the panel to talk with the agent the upload icon is there, do I have to do something to enable the file uploads?
Regards.

**Comment by tianjing-li** [comment]
@micuentadecasa this is fixed now
