### ISSUE TITLE
Better Errors for Backend Failure

### ISSUE THREAD

**Issue by bcicc** [cohere-ai/cohere-toolkit#806]
### What is the issue?

When the backend isn't available there is a misleading frontend error message. One can easily recreate this by commenting out the uvicorn launch command in the backend Dockerfile (disabling the backend web server). Navigating to the web app then shows the following error:
![image](https://github.com/user-attachments/assets/9eb8591e-3c06-472f-bd33-9f685793f288)

**Comment by tianjing-li** [comment]
@bcicc this is a great point, without the docker container logs it's hard to know when the backend fails from the client. Will make an internal ticket to look into how best to address this.

In this meantime, you can check the backend logs with `make attach` or `docker compose logs` when running the backend locally, it'll give you more insight

**Comment by tianjing-li** [comment]
@bcicc This is in progress

**Comment by tianjing-li** [comment]
@bcicc added #810
