### ISSUE TITLE
401 API Token issue

### ISSUE THREAD

**Issue by anespo** [cohere-ai/cohere-toolkit#857]
### What is the issue?

Hi Team,
I installed cohere toolkit in one of my Mac and I found this issue:
Unable to generate a response since an error was encountered. 

Warning
status_code: 401, body: {'message': 'invalid api token'}

But I double checked and the API Key in my cohere dashboard is correct and I wrote it in the .env file.
Can you help me with that please.
Tony

**Comment by anespo** [comment]
resolved

**Comment by brinikki** [comment]
how did you fix it? im having the same issue
