### ISSUE TITLE
Poetry install should be part of steps, not additional tips

### ISSUE THREAD

**Issue by ai-yann** [cohere-ai/cohere-toolkit#881]
### What improvement(s) are you suggesting?

Since poetry is built into `make first-run`, it should be included in https://github.com/cohere-ai/cohere-toolkit/tree/main?tab=readme-ov-file#local :

You will need to have [Docker](https://www.docker.com/products/docker-desktop/), [Docker-compose >= 2.22](https://docs.docker.com/compose/install/), and [Poetry](link to installation instructions) installed. [Go here for a more detailed setup.](https://github.com/cohere-ai/cohere-toolkit/blob/main/docs/setup.md)

Instead of having it https://github.com/cohere-ai/cohere-toolkit/blob/main/docs/setup.md#additional-tips

Because when you follow those instructions on the main README, it fails on poetry:
<img width="560" alt="Screenshot 2024-12-16 at 4 52 05 PM" src="https://github.com/user-attachments/assets/a11e6ddc-9812-42ed-8011-40f6ea024a1b" />

**Comment by tianjing-li** [comment]
Great point, this is addressed now
