### ISSUE TITLE
Add csv file type for document upload

### ISSUE THREAD

**Issue by elaineg** [cohere-ai/cohere-toolkit#91]
### What feature(s) would you like to see?

Current behaviour: 
The default file upload tool added to the toolkit only parses PDFs.

Expected behaviour: 
1. Add a tool that can parse csv files into string and send to model into available default tools 
2. When a csv is uploaded, automatically select the csv file tool to be used with it (similar to PDF) 

We would love to see even more file types supported but I will close this when csv is supported.

**Comment by tianjing-li** [comment]
Can spec this out when prioritized

**Comment by Mohyuddin1973** [comment]
Send me the CSV please
